version: "3"

services:
  frontend:
    build:
      context: ./docker/frontend/
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"

  backend:
    build:
      context: ./docker/backend/
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    # depends_on:
    #   - db

  redis:
    image: "redis:6.2.1-alpine"

  # db:
  #   image: "postgres:13.2"
  #   environment: 
  #   - POSTGRES_DB=postgres
  #   - POSTGRES_USER=postgres
  #   - POSTGRES_PASSWORD=postgres
  #   - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C

  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #   ports:
  #     - "15432:5432"
  #   restart: always
  
  # volumes: 
  #   dbdata: